name: CI

on:
  push:
    branches:
      - main
      - development

    tags:
      - v*

    paths-ignore:
      - README.md

  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Calc coverage
        run: make coverage

      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9

      - name: Coveralls
        uses: coverallsapp/github-action@v2.0.0
        with:
          github-token: ${{ secrets.github_token }}
          file: coverage.lcov